### ISSUE TITLE
封包大小錯誤

### ISSUE THREAD

**Issue by RozenAstrayChen** [jk195417/FCU-Final-Project#1]
第二章 Raspberry Pi : 使用藍芽 Dongle 與安裝 BlueZ
在解釋封包這裡有誤
![2016-11-23 6 57 14](https://cloud.githubusercontent.com/assets/19503080/20559294/ba46c5e6-b1ae-11e6-900b-26c6952d586e.png)
應修正成
iBeacon Prefix 9 bytes
uuid 16 bytes
major 2bytes
minor 2bytes
tx power 1 bytes

**Comment by jk195417** [comment]
感謝回報
